# Generated by Django 2.2.1 on 2019-08-17 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='llegada',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Llegada'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='salida',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Salida'),
        ),
    ]
