# Generated by Django 2.2.1 on 2019-08-18 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190817_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='llegada',
            field=models.DateField(default=datetime.date(2019, 9, 21), verbose_name='Llegada'),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='salida',
            field=models.DateField(default=datetime.date(2019, 9, 21), verbose_name='Salida'),
        ),
    ]
