# Generated by Django 2.2.1 on 2019-08-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190818_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitado',
            name='es_menor',
        ),
    ]
