# Generated by Django 2.2.1 on 2019-08-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_invitado_es_menor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='jueves19playa',
            field=models.BooleanField(default=False, verbose_name='jueves19playa'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='lunes16velero',
            field=models.BooleanField(default=False, verbose_name='lunes16velero'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='martes17playa',
            field=models.BooleanField(default=False, verbose_name='martes17playa'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='miercoles18comida',
            field=models.BooleanField(default=False, verbose_name='miercoles18comida'),
        ),
    ]
