# Generated by Django 2.2.4 on 2019-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190821_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='viernes20preboda',
            field=models.BooleanField(default=False, verbose_name='viernes20preboda'),
        ),
    ]
